version: "3"
services:
  db:
    # コンテナ名の指定
    container_name: rails_todo_db
    # イメージの指定
    image: postgres:14.2-alpine
    # データの永続化（ホスト側の tmp/db ディレクトリにマウントする）
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    # 環境変数の指定（初期設定値）
    environment:
      POSTGRES_PASSWORD: password
  web:
    # コンテナ名の指定
    container_name: rails_todo_web
    # Dockerfile のあるディレクトリのパスを指定（image か build を必ず指定する必要がある）
    build: .
    # デフォルトのコマンド指定（Rails 特有の問題解消と Rails 立ち上げを指定している）
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    # データの永続化（ホスト側のカレントディレクトリにマウントする）
    volumes:
      - .:/myapp
    # ポートの指定（外部からのアクセス時のポート：Docker コンテナからアクセス時のポート）
    ports:
      - "3000:3000"
    # 依存関係の指定（db が起動した後に、web が起動するようになる）
    depends_on:
      - db
